### ISSUE TITLE
Catch

### ISSUE THREAD

**Issue by Mu7ammadAbed** [GSG-G11/Photo-Gallery#42]
Where is the catch ?
https://github.com/GSG-G11/Photo-Gallery/blob/8139322ab3f893d0506d7386effcf21a84bf1027/server/helpers/fetchDataFromExternalApi.js#L3-L4

**Comment by zaher-aa** [comment]
@Mu7ammadAbed We are handling the error in another file
https://github.com/GSG-G11/Photo-Gallery/blob/5843b95e3f703aa1c3e4af9b4f59845ff55c083e/server/controllers/handleSearch.js#L7-L9
